#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

printf "\n"
printf "=== Pre-commit check start ===\n"
printf "\n"
printf "> run linting and formating...\n"
printf "\n"
npx lint-staged
printf "\n"
printf "> run test...\n"
printf "\n"
yarn test
printf "\n"
